# Generated by Django 5.2.7 on 2025-10-20 02:04

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import read.utils.model_mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updated_date",
                    models.DateField(
                        auto_now=True, null=True, verbose_name="Updated Date"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="School Name", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updated_date",
                    models.DateField(
                        auto_now=True, null=True, verbose_name="Updated Date"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "marked_for_deletion",
                    models.DateField(
                        blank=True,
                        help_text="Date when this record was marked for deletion",
                        null=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_initial",
                    models.CharField(
                        blank=True, max_length=1, null=True, verbose_name="Last Initial"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Automatically generated from first name and last initial",
                        max_length=210,
                        null=True,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Whether this record has been verified",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("parent", "Parent"),
                            ("administrator", "Administrator"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "change_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "password_change_required",
                    models.BooleanField(
                        default=False,
                        help_text="User must change password on next login",
                        verbose_name="Password Change Required",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.school",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReadingGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updated_date",
                    models.DateField(
                        auto_now=True, null=True, verbose_name="Updated Date"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Name of the record", max_length=255
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "managers",
                    models.ManyToManyField(
                        limit_choices_to=models.Q(
                            ("user_type", "teacher"),
                            ("user_type", "administrator"),
                            _connector="OR",
                        ),
                        related_name="managed_reading_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        limit_choices_to={"user_type": "student"},
                        related_name="reading_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="The school this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.school",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updated_date",
                    models.DateField(
                        auto_now=True, null=True, verbose_name="Updated Date"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Name of the record", max_length=255
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        limit_choices_to={"user_type": "student"},
                        related_name="students_classrooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"user_type": "teacher"},
                        related_name="teachers_classrooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="The school this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.school",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudentParentRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updated_date",
                    models.DateField(
                        auto_now=True, null=True, verbose_name="Updated Date"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "parent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="The school this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["school", "parent"],
                        name="users_stude_school__a3013e_idx",
                    ),
                    models.Index(
                        fields=["school", "student"],
                        name="users_stude_school__6f8178_idx",
                    ),
                ],
                "unique_together": {("student", "parent")},
            },
            bases=(models.Model, read.utils.model_mixins.SchoolConsistencyMixin),
        ),
    ]
