# Generated by Django 5.2.5 on 2025-08-20 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='students',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('administrator', 'Administrator')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentparentrelation',
            name='parent',
            field=models.ForeignKey(limit_choices_to={'user_type': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='children_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentparentrelation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school'),
        ),
        migrations.AlterField(
            model_name='studentparentrelation',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='studentparentrelation',
            unique_together={('student', 'parent')},
        ),
        migrations.AddIndex(
            model_name='studentparentrelation',
            index=models.Index(fields=['school', 'parent'], name='users_stude_school__a3013e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentparentrelation',
            index=models.Index(fields=['school', 'student'], name='users_stude_school__6f8178_idx'),
        ),
    ]
