# Generated by Django 5.2.5 on 2025-08-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_change_required',
            field=models.BooleanField(default=False, help_text='User must change password on next login', verbose_name='Password Change Required'),
        ),
    ]
