# Generated by Django 5.2.5 on 2025-09-09 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_password_change_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='readinggroup',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='classroom',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this record is active', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this record is active', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the record', max_length=255),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(default=0, help_text='The school this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='users.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this record is active', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, default=None, help_text='Automatically generated from first name and last initial', max_length=210, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='marked_for_deletion',
            field=models.DateField(blank=True, help_text='Date when this record was marked for deletion', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verified',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this record has been verified'),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the record', max_length=255),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='school',
            field=models.ForeignKey(help_text='The school this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='users.school'),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='studentparentrelation',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='studentparentrelation',
            name='school',
            field=models.ForeignKey(help_text='The school this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='users.school'),
        ),
    ]
