# Generated by Django 5.2.7 on 2025-10-20 02:04

import django.core.validators
import read.utils.model_mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassroomInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updated_date",
                    models.DateField(
                        auto_now=True, null=True, verbose_name="Updated Date"
                    ),
                ),
                ("teacher_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("high_engagement", "High Engagement Strategies"),
                            ("goal_achievement", "Goal Achievement Techniques"),
                            ("reading_variety", "Encouraging Reading Variety"),
                            ("student_motivation", "Student Motivation Methods"),
                            ("classroom_management", "Classroom Management"),
                            ("progress_tracking", "Progress Tracking"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=1000)),
                (
                    "implementation_tips",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "success_metric",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pages_increase", "Pages read increased"),
                            ("engagement_increase", "Student engagement increased"),
                            ("goal_completion", "Goal completion improved"),
                            ("reading_frequency", "Reading frequency increased"),
                            ("book_variety", "Book variety expanded"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("allow_contact", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="DailyGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("pages", "Pages"), ("minutes", "Minutes")],
                        default="pages",
                        max_length=10,
                    ),
                ),
                ("value", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InsightHelpful",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updated_date",
                    models.DateField(
                        auto_now=True, null=True, verbose_name="Updated Date"
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "title",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("pages", models.IntegerField(blank=True, null=True)),
                ("minutes", models.IntegerField(blank=True, null=True)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date", "-created_date"],
            },
            bases=(models.Model, read.utils.model_mixins.SchoolConsistencyMixin),
        ),
        migrations.CreateModel(
            name="PointsHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_earned", models.IntegerField()),
                ("reason", models.CharField(max_length=200)),
                ("new_total", models.IntegerField()),
                ("new_level", models.IntegerField()),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-earned_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "progress_data",
                    models.JSONField(
                        default=dict,
                        help_text="JSON data about how the badge was earned",
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("current_level", models.IntegerField(default=1)),
                ("points_to_next_level", models.IntegerField(default=100)),
                (
                    "current_streak",
                    models.IntegerField(
                        default=0, help_text="Current daily reading streak"
                    ),
                ),
                (
                    "longest_streak",
                    models.IntegerField(
                        default=0, help_text="Longest reading streak achieved"
                    ),
                ),
                ("total_books_read", models.IntegerField(default=0)),
                ("total_pages_read", models.IntegerField(default=0)),
                ("total_minutes_read", models.IntegerField(default=0)),
                ("last_activity", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TotalGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
                ("total", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("reading", "Reading Achievement"),
                            ("consistency", "Consistency & Habits"),
                            ("milestone", "Milestone Achievement"),
                            ("special", "Special Achievement"),
                            ("social", "Social Achievement"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(help_text="FontAwesome icon class", max_length=50),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object defining achievement criteria",
                    ),
                ),
                (
                    "points_value",
                    models.IntegerField(
                        default=10, help_text="Points awarded for earning this badge"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "difficulty", "name"],
                "unique_together": {("name", "difficulty")},
            },
        ),
    ]
