# Generated by Django 5.2.5 on 2025-09-11 16:07

import django.core.validators
import django.db.models.deletion
import read.utils.model_mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_classroom_options_alter_customuser_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('reading', 'Reading Achievement'), ('consistency', 'Consistency & Habits'), ('milestone', 'Milestone Achievement'), ('special', 'Special Achievement'), ('social', 'Social Achievement')], max_length=20)),
                ('difficulty', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20)),
                ('icon', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('criteria', models.JSONField(default=dict, help_text='JSON object defining achievement criteria')),
                ('points_value', models.IntegerField(default=10, help_text='Points awarded for earning this badge')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'difficulty', 'name'],
                'unique_together': {('name', 'difficulty')},
            },
        ),
        migrations.CreateModel(
            name='ClassroomInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('teacher_hash', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(choices=[('high_engagement', 'High Engagement Strategies'), ('goal_achievement', 'Goal Achievement Techniques'), ('reading_variety', 'Encouraging Reading Variety'), ('student_motivation', 'Student Motivation Methods'), ('classroom_management', 'Classroom Management'), ('progress_tracking', 'Progress Tracking')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('implementation_tips', models.TextField(blank=True, max_length=500, null=True)),
                ('success_metric', models.CharField(blank=True, choices=[('pages_increase', 'Pages read increased'), ('engagement_increase', 'Student engagement increased'), ('goal_completion', 'Goal completion improved'), ('reading_frequency', 'Reading frequency increased'), ('book_variety', 'Book variety expanded')], max_length=20, null=True)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('allow_contact', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pages', 'Pages'), ('minutes', 'Minutes')], default='pages', max_length=10)),
                ('value', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.classroom')),
                ('reading_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.readinggroup')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InsightHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reading_logs.classroominsight')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('date', models.DateField(db_index=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(help_text='The school this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='users.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_date'],
            },
            bases=(models.Model, read.utils.model_mixins.SchoolConsistencyMixin),
        ),
        migrations.CreateModel(
            name='PointsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('new_total', models.IntegerField()),
                ('new_level', models.IntegerField()),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress_data', models.JSONField(default=dict, help_text='JSON data about how the badge was earned')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading_logs.badge')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('current_level', models.IntegerField(default=1)),
                ('points_to_next_level', models.IntegerField(default=100)),
                ('current_streak', models.IntegerField(default=0, help_text='Current daily reading streak')),
                ('longest_streak', models.IntegerField(default=0, help_text='Longest reading streak achieved')),
                ('total_books_read', models.IntegerField(default=0)),
                ('total_pages_read', models.IntegerField(default=0)),
                ('total_minutes_read', models.IntegerField(default=0)),
                ('last_activity', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
                ('student', models.OneToOneField(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='points_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TotalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('total', models.PositiveIntegerField(default=0)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.classroom')),
                ('reading_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.readinggroup')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='classroominsight',
            index=models.Index(fields=['school', 'category', '-created_date'], name='reading_log_school__8a9ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='classroominsight',
            index=models.Index(fields=['school', '-helpful_count'], name='reading_log_school__498d92_idx'),
        ),
        migrations.AddIndex(
            model_name='classroominsight',
            index=models.Index(fields=['school', '-created_date'], name='reading_log_school__34c52b_idx'),
        ),
        migrations.AddIndex(
            model_name='insighthelpful',
            index=models.Index(fields=['insight', 'teacher_hash'], name='reading_log_insight_3704a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='insighthelpful',
            unique_together={('insight', 'teacher_hash')},
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['school', 'student', 'date'], name='reading_log_school__62bbe9_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['school', 'date'], name='reading_log_school__d5c106_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['student', 'date'], name='reading_log_student_aaae98_idx'),
        ),
        migrations.AddConstraint(
            model_name='log',
            constraint=models.CheckConstraint(condition=models.Q(('pages__gte', 0), ('pages__isnull', True), _connector='OR'), name='pages_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='log',
            constraint=models.CheckConstraint(condition=models.Q(('minutes__gte', 0), ('minutes__isnull', True), _connector='OR'), name='minutes_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='studentbadge',
            unique_together={('student', 'badge')},
        ),
    ]
