# Generated by Django 5.2.7 on 2025-10-20 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reading_logs", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classroominsight",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.school"
            ),
        ),
        migrations.AddField(
            model_name="dailygoal",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.classroom",
            ),
        ),
        migrations.AddField(
            model_name="dailygoal",
            name="reading_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.readinggroup",
            ),
        ),
        migrations.AddField(
            model_name="dailygoal",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.school"
            ),
        ),
        migrations.AddField(
            model_name="dailygoal",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="insighthelpful",
            name="insight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="helpful_votes",
                to="reading_logs.classroominsight",
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="school",
            field=models.ForeignKey(
                help_text="The school this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.school",
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="pointshistory",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.school"
            ),
        ),
        migrations.AddField(
            model_name="pointshistory",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentbadge",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reading_logs.badge"
            ),
        ),
        migrations.AddField(
            model_name="studentbadge",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.school"
            ),
        ),
        migrations.AddField(
            model_name="studentbadge",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="earned_badges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentpoints",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.school"
            ),
        ),
        migrations.AddField(
            model_name="studentpoints",
            name="student",
            field=models.OneToOneField(
                limit_choices_to={"user_type": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="totalgoal",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.classroom",
            ),
        ),
        migrations.AddField(
            model_name="totalgoal",
            name="reading_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.readinggroup",
            ),
        ),
        migrations.AddField(
            model_name="totalgoal",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.school"
            ),
        ),
        migrations.AddField(
            model_name="totalgoal",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="classroominsight",
            index=models.Index(
                fields=["school", "category", "-created_date"],
                name="reading_log_school__8a9ec9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classroominsight",
            index=models.Index(
                fields=["school", "-helpful_count"],
                name="reading_log_school__498d92_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classroominsight",
            index=models.Index(
                fields=["school", "-created_date"],
                name="reading_log_school__34c52b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="insighthelpful",
            index=models.Index(
                fields=["insight", "teacher_hash"],
                name="reading_log_insight_3704a7_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="insighthelpful",
            unique_together={("insight", "teacher_hash")},
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(
                fields=["school", "student", "date"],
                name="reading_log_school__62bbe9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(
                fields=["school", "date"], name="reading_log_school__d5c106_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(
                fields=["student", "date"], name="reading_log_student_aaae98_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="log",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pages__gte", 0), ("pages__isnull", True), _connector="OR"
                ),
                name="pages_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="log",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("minutes__gte", 0), ("minutes__isnull", True), _connector="OR"
                ),
                name="minutes_non_negative",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentbadge",
            unique_together={("student", "badge")},
        ),
    ]
