# Generated by Django 5.2.7 on 2025-10-20 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading_logs", "0002_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointshistory",
            name="earned_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="studentbadge",
            name="earned_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="studentpoints",
            name="current_level",
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name="studentpoints",
            name="last_activity",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentpoints",
            name="total_pages_read",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="studentpoints",
            name="total_points",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="totalgoal",
            name="end",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="totalgoal",
            name="start",
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="dailygoal",
            index=models.Index(
                fields=["school", "student"], name="reading_log_school__f62e5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailygoal",
            index=models.Index(
                fields=["school", "classroom"], name="reading_log_school__382787_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailygoal",
            index=models.Index(
                fields=["school", "reading_group"],
                name="reading_log_school__284568_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pointshistory",
            index=models.Index(
                fields=["student", "-earned_at"], name="reading_log_student_15cb72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointshistory",
            index=models.Index(
                fields=["school", "-earned_at"], name="reading_log_school__6140fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointshistory",
            index=models.Index(
                fields=["student", "earned_at"], name="reading_log_student_1488d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentbadge",
            index=models.Index(
                fields=["student", "-earned_at"], name="reading_log_student_2534c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentbadge",
            index=models.Index(
                fields=["school", "badge"], name="reading_log_school__b91b2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentbadge",
            index=models.Index(
                fields=["school", "-earned_at"], name="reading_log_school__39de90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentpoints",
            index=models.Index(
                fields=["school", "-total_points"],
                name="reading_log_school__bdf928_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentpoints",
            index=models.Index(
                fields=["school", "-current_level"],
                name="reading_log_school__89a9ac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentpoints",
            index=models.Index(
                fields=["school", "-total_pages_read"],
                name="reading_log_school__55e962_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentpoints",
            index=models.Index(
                fields=["-last_activity"], name="reading_log_last_ac_9e59b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="totalgoal",
            index=models.Index(
                fields=["school", "student", "start", "end"],
                name="reading_log_school__d4d4b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="totalgoal",
            index=models.Index(
                fields=["school", "classroom"], name="reading_log_school__c56a3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="totalgoal",
            index=models.Index(
                fields=["school", "reading_group"],
                name="reading_log_school__838a9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="totalgoal",
            index=models.Index(
                fields=["start", "end"], name="reading_log_start_9bbd4b_idx"
            ),
        ),
    ]
