# Generated by Django 5.2.5 on 2025-08-20 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_logs', '0002_initial'),
        ('users', '0002_add_tracking_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='type',
            field=models.CharField(choices=[('pages', 'Pages'), ('minutes', 'Minutes')], default='pages', max_length=10),
        ),
        migrations.AlterField(
            model_name='log',
            name='author',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school'),
        ),
        migrations.AlterField(
            model_name='log',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['school', 'student', 'date'], name='reading_log_school__62bbe9_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['school', 'date'], name='reading_log_school__d5c106_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['student', 'date'], name='reading_log_student_aaae98_idx'),
        ),
        migrations.AddConstraint(
            model_name='log',
            constraint=models.CheckConstraint(condition=models.Q(('pages__gte', 0), ('pages__isnull', True), _connector='OR'), name='pages_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='log',
            constraint=models.CheckConstraint(condition=models.Q(('minutes__gte', 0), ('minutes__isnull', True), _connector='OR'), name='minutes_non_negative'),
        ),
    ]
